spring.application.name=AuthService
server.port=8087
server.address=0.0.0.0

management.endpoints.web.exposure.include=*


# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true