spring.application.name=api-gateway
server.port=8765
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

### Enable Eureka Client
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#
### Auth Service Route
spring.cloud.gateway.routes[0].id=AuthService
spring.cloud.gateway.routes[0].uri=lb://AuthService
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
#
### Shares Service Route
#spring.cloud.gateway.routes[1].id=Shares
#spring.cloud.gateway.routes[1].uri=lb://Shares
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/shares/**
#
### Management Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
#
### Logging for Debugging
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.com.netflix.discovery=DEBUG
#logging.level.org.springframework.cloud.netflix.eureka=DEBUG
#
#
