spring.application.name=notification-service
server.port=8082

server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/jaybee
spring.datasource.username=yousefalm
spring.datasource.password=Ym123456789

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=*

# ? Enable Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG
