spring.application.name=main-service
server.port=8080
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/jaybee
spring.datasource.username=yousefalm
spring.datasource.password=Ym123456789
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=*
jwt.secret=secret

#openai.api.key=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
openai.api.key=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
spring.redis.host=redis
spring.redis.port=6379

spring.config.import=optional:configserver:


logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Twilio OTP Config
twilio.AccountSID=AC27e7528f24dce2c6ee7fcbeff30881d9
twilio.AuthToken=303bac5da86f649e8c091d85a555e42e
twilio.phoneNumber=+15075788264

# Swagger
# Enable OpenAPI and Swagger UI
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.paths-to-match=/**
#server.servlet.context-path=/api

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG