spring.application.name=shares-service
spring.datasource.url=jdbc:postgresql://localhost:5432/myDataBase
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=*
jwt.secret=secret
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#Twilio OTP Config
twilio.AccountSID=ACe57769b28f3343d86b354406184f1e04
twilio.AuthToken=58da2dc96fae96cb079b28dadb5fa9ad
twilio.phoneNumber=+1 361 423 2430
# Eureka client configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#logging.level.com.netflix.discovery=DEBUG
#logging.level.com.netflix.eureka=DEBUG
#security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
#security.jwt.expiration-time=604800000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# Eureka client configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#logging.level.com.netflix.discovery=DEBUG
#logging.level.com.netflix.eureka=DEBUG


