spring.application.name=shares-service
server.port=8080
server.address=0.0.0.0
spring.datasource.url=jdbc:postgresql://localhost:5432/myDataBase
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=*
jwt.secret=secret

spring.redis.host=localhost
spring.redis.port=6379


logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Twilio OTP Config
twilio.AccountSID=AC791abeb42be6dbf6f91b56113c2e4537
twilio.AuthToken=18e2106c6efccb1bc0b0b9c7ad3932fe
twilio.phoneNumber=+15153163362

# Swagger
# Enable OpenAPI and Swagger UI
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.paths-to-match=/**
#server.servlet.context-path=/api

# Eureka client configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#logging.level.com.netflix.discovery=DEBUG
#logging.level.com.netflix.eureka=DEBUG